name: Backend Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Install dependencies
        working-directory: ./
        run: npm install

      - name: Run tests
        working-directory: ./
        run: npm run test